dev:
  shouldDeploy: false # Should the stack be deployed
  stackName: "" # Name of the stack
  vpcName: "" # Name of the VPC
  pgSecurityGroup: "" # Security group name for the Postgres database
  dbName: "" # Name of the database
  ecrRepository: "" # Name of the ECR repository
  keyName: "" # PEM key name to ssh into db instance
  region: "" # Region of the stack
  githubOwner: "" # Owner of the github repository
  githubRepo: "" # Name of the github repository
  githubBranch: "" # Branch of the github repository
  githubAccessTokenSecret: "" # Secret name of the github access token
  pipelineContainerName: "" # Name of the container in the pipeline
  pipelineName: "" # Name of the pipeline

prod:
  shouldDeploy: true # Should the stack be deployed
  stackName: "" # Name of the stack
  vpcName: "" # Name of the VPC
  pgSecurityGroup: "" # Security group name for the Postgres database
  dbName: "" # Name of the database
  ecrRepository: "" # Name of the ECR repository
  key: "" # PEM key name to ssh into db instance
  region: "" # Region of the stack
  githubOwner: "" # Owner of the github repository
  githubRepo: "" # Name of the github repository
  githubBranch: "" # Branch of the github repository
  githubAccessTokenSecret: "" # Secret name of the github access token
  pipelineContainerName: "" # Name of the container in the pipeline
  pipelineName: "" # Name of the pipeline